github/paste-markdown

src/index.js, src/paste-markdown-text.js
Pastes markdown formatted text from the clipboard with the custom text/x-gfm mime type if available. Pairs with`@github/quote-selection` which copies the text/x-gfm data onto the clipboard.
/cc https://github.com/github/quote-selection/pull/9
=> Paste markdown text from clipboard

src/paste-markdown-image-link.js, src/text.js
- The `paste` & `drop` handlers now fall back to native behavior if no image links were found in the data transfer. This avoids an extra newline when pasting a plain link.
- Do not call `insertText()` more than once. This avoids triggering the 'change' event N times if N items were pasted/dropped.
- Correctly position cursor after operation if extra newline was inserted.
- Correctly replace existing selection on paste.
=> Fix pasting a single link in Safari

.eslintignore, .eslintrc.json, .flowconfig, index.d.ts, karma.config.js, package-lock.json, package.json, rollup.config.js, src/index.js.flow, src/index.ts, src/paste-markdown-image-link.ts, src/paste-markdown-table.ts, src/paste-markdown-text.ts, src/text.ts, test/.eslintrc.json, tsconfig.json
This replace Flow with TypeScript and removes babel.
Ref: 
- The official rollup TS plugin doesn't support generating TS declarations https://github.com/rollup/plugins/issues/61
- `typescript2` does 🙃 , and is used by a good number of repositories and being maintained https://github.com/ezolenko/rollup-plugin-typescript2#declarations
=> Replace flow + babel with tsc

README.md, examples/index.html, src/paste-markdown-table.ts, test/test.js
In dotcom we use `<table>` for as HTML parser boundaries in comments and for line/column in blobs. These tables should not be turned into markdown tables when they get copy-pasted.
Previously we use `js-comment`/`js-blob-*`/`js-diff-*` as pointers to skip certain tables. This PR generalize them so it will be easier to mark future tables as not pastable as markdown without altering the library code or subscribing them into `js-` prefixed classes.
I was gonna call this `[data-layout-table]` but opted to name it `[data-paste-markdown-skip]` instead because:
1. I thought "layout tables" was fitting because they are tables used for their display characteristics instead of semantics, hence should not be parsed as tables. But turns out, many of our cases are actual data tables that just aren't …
=> Prevent parsing table[data-paste-markdown-skip]

src/paste-markdown-table.ts, test/test.js
Before this change, we would fish out the table element from the pasted value, convert that into a markdown table, and inject that markdown table into the textarea element.
After the change in this pull request, we will retain the original text and only replace the HTML table.
=> Retain other text around HTML tables

src/paste-markdown-table.ts, test/test.js, tsconfig.json
Instead of fishing out the only table in the clipboard payload, we query all table elements and convert them to markdown tables.
=> Parse all tables in clipboard payload

.github/workflows/nodejs.yml
The `Build` workflow for [this PR](https://github.com/github/paste-markdown/pull/23) is not running as I opened it from a forked repository (since I don't have write permissions to this repository) and since the workflow only listens for `push` events.
This PR should fix this and make the `Build` workflow run for [`pull_request` `opened`, `synchronize` and `reopened` events](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request).
=> Make `Build` workflow run for PRs from forked repos

README.md, examples/index.html, src/index.ts, src/paste-markdown-link.ts, src/text.ts, test/test.js
This pull request adds pasting URLs on selected text as Markdown links.
In order to test this new functionality:
1. Copy this URL `https://docs.github.com` or any other URL
1. Go to https://paste-markdown-steffen-testing.vercel.app/examples
1. Write something like: `You can find the docs here.`
1. Select `here`
1. Paste URL with <kbd>cmd + v</kbd>
Result: You should now see a Markdown link: `[here](https://docs.github.com)`
=> Add pasting URLs on selected text as Markdown links

package.json
Our `tsc` in `github/github` complains about missing type declarations:
```
node_modules/@github/paste-markdown/dist/index.d.ts(1,78): error TS2307: Cannot find module './paste-markdown-image-link' or its corresponding type declarations.
node_modules/@github/paste-markdown/dist/index.d.ts(2,68): error TS2307: Cannot find module './paste-markdown-link' or its corresponding type declarations.
node_modules/@github/paste-markdown/dist/index.d.ts(3,70): error TS2307: Cannot find module './paste-markdown-table' or its corresponding type declarations.
node_modules/@github/paste-markdown/dist/index.d.ts(4,68): error TS2307: Cannot find module './paste-markdown-text' or its corresponding type declarations.
```
This PR should resolve this.
Not sure if you have a preference for listing each file …
=> Include all `dist` files in package

examples/index.html, src/index.ts, src/paste-markdown-html.ts, test/test.js, tsconfig.json
👋 🦄 🐳 Hello! This pull request adds support for converting multiple links from an HTML copy source into a comment box upon paste. Previous copy/paste functionality is unchanged, e.g. when pasting a plaintext link onto a selection.
See GIF and internal tracking issue for more context 🍿 📺:
=> Paste multiple links into markdown via comment box

.eslintrc.json, src/paste-markdown-html.ts, test/test.js
Following https://github.com/github/paste-markdown/pull/35 and https://github.com/github/paste-markdown/pull/38, we also need to leave "special" GitHub links intact without Markdownifying them, e.g. `@octocat`, `#35`.
A list like:
- @imnotjohnbo (username)
- #81 (issue)
- https://github.com/imjohnbo/playground/issues/81 (issue)
- https://github.com/imjohnbo/playground/pull/75 (PR)
- https://github.com/imjohnbo/playground/discussions/73 (discussion)
- https://github.com/imjohnbo/playground/commit/34016755a04332fbebde0991cde758fce05d1764 (commit)
- https://github.com/imjohnbo/playground/compare/master...add-fix (compare)
- https://github.com/advisories/GHSA-93q8-gq69-wqmw (CVE)
Should be able to be copied from the comment and pasted as:
```
- @imnotjohnbo (username)
- #81 (issue)
- …
```
=> Fix "special" link paste in GitHub

src/paste-markdown-html.ts, test/test.js
👋 Hello, this PR should fix https://github.com/github/paste-markdown/issues/45 by:
1. ([src](https://github.com/imjohnbo/paste-markdown/blob/b5eec8adb7d45fd2a63aab6629c87ea9acc6e93f/src/paste-markdown-html.ts#L33)) Getting all elements from HTML clipboard.
2. ([src](https://github.com/imjohnbo/paste-markdown/blob/b5eec8adb7d45fd2a63aab6629c87ea9acc6e93f/src/paste-markdown-html.ts#L67)) Finding the first occurrence of the matching text in the plaintext clipboard after a search index.
3. ([src](https://github.com/imjohnbo/paste-markdown/blob/b5eec8adb7d45fd2a63aab6629c87ea9acc6e93f/src/paste-markdown-html.ts#L70)) If this is a link, linkify it as before and increment the search index.
4. ([src](https://github.com/imjohnbo/paste-markdown/blob/b5eec8adb7d45fd2a63aab6629c87ea9acc6e93f/src/paste …
=> Fix: target correct link when multiple matches are present

src/paste-markdown-html.ts, test/test.js
This PR adds logic to skip formatting `html` pastebin data if the user pastes directly after a `@` sign. 
In the future this can be extended to support a few `ignore_characters` or strings as input when the library is loaded.
=> do not format as markdown when pasting after at mention

src/paste-markdown-link.ts, test/test.js
The bugfix I introduced in https://github.com/github/paste-markdown/pull/65 caused a regression because we were no longer accounting for paths after the initial slash at the end of the domain. This PR updates the URL validation to rely on creating a new `URL` instead. This will throw an exception if the URL is not valid. 
In addition, we check to make sure that the parsed href matches the original URL passed in. This accounts for cases like `http://example.com and some other stuff`, which would count as a valid URL (parsed to `http://example.com%20and%20some%20other%20stuff`), but not be content that we actually want to treat as a URL. 
Even with this extra check, felt a lot nicer than needing to deal with a RegExp 😅
=> Update to support longer URLs

README.md, src/index.ts, src/option-config.ts, src/paste-keyboard-shortcut-helper.ts, src/paste-markdown-link.ts, test/test.js
We wish to be able to have granual control over specifically the behaviour of whether to linkify when pasting a link over selected text. This pull request extends the current code base to support granual config support on the installation of the package, at this time, it only adds one control being for the `paste-markdown-link` (urlLinks in our API params).
This config, which is default set to false (undefined | false), is the existing behaviour and therefore not a breaking change.
The approach would therefore add the following "new" behaviour, given the pasteLinkAsPlainTextOverSelectedText flag for `paste-markdown-link`, and depending on whether the skipFormattingFlag is on/off:
- paste plain text is on, no skip flag -> paste as plain
- paste plain text is on, skip flag -> try linkify
- …
=> Add architecture for granual pasteAsPlainText support

.github/workflows/publish.yml
The `publish` workflow was skipping the [`postpublish` script](https://github.com/github/paste-markdown/blob/main/package.json#L17) that publishes this package to the GitHub Package Registry. This PR removes the `--ignore-scripts` flag in that workflow that was preventing the `postpublish` script from running
=> Publish to GitHub Package Registry in publish action

.github/workflows/publish.yml, package.json
Makes publishing to npm and github registry independent
Unlike before, If the [first one fails](https://github.com/github/paste-markdown/actions/runs/3178114867), it would not stop the second
=> Independent publishing

src/paste-markdown-table.ts, test/test.js
Resolves https://github.com/github/primer/issues/2532
This came in from a support escalation: it is possible to create a ReDOS crash on paste of a table with a (fairly contrived) clipboard contents. Thanks @P0cas for reporting this!
The crash is due to a [Catastrophic Backtracking](https://www.regular-expressions.info/catastrophic.html) regex in the `table` plugin, which is triggered by the following clipboard contents:
```js
example.oncopy = e => {
e.preventDefault()
const badTable = '<table'.repeat(99999) + '<div><table></div>'
e.clipboardData.setData('text/html', badTable)
}
```
While the problem is contrived the fix is fairly simple: rather than use a regex to insert the formatted table, we can just splice it in directly.
=> Avoid ReDOS on table paste

src/paste-markdown-html.ts, test/test.js
related to https://github.com/github/html_pipeline/issues/76
This pull request to the codebase includes changes to improve the handling of GitHub team mentions in the `paste()` function. The most important changes include adding a new test case to check that team handles are not rendered as markdown, and updating the `linkify()` function to check if a link is a team mention using the new `isTeamMention()` function.
Main interface changes:
* <a href="diffhunk://#diff-c872021d2cf4d6e6c076e2589b1a7cb5ccf0a1e39f1e45c4734ba5897fbdd57dL126-R126">`src/paste-markdown-html.ts`</a>: Updated the `linkify()` function to check if a link is a team mention using the new `isTeamMention()` function, and returns the label as markdown if it is a team or user mention. <a …
=> team mention pasting

src/paste-markdown-html.ts, test/test.js
Hi 👋🏼, this is an attempt to fix the issue below where Pasting HTML with links can place the link in the wrong place
- https://github.com/github/issues/issues/5429
The [original fix was submitted here](https://github.com/github/paste-markdown/pull/50). This PR attempts to look at a few edge cases that came up as shown indicated in the issue above. These include:
> ```
> foo bar baz [bar](https://www.abcxyz.com)
> ```
> Which would result to the following after pasting
> ```
> foo [bar](https://www.abcxyz.com/) baz bar
> ```
and
> ```
> foo bar 
> bar baz [bar](https://www.abcxyz.org/) 
>  
> baz [baz](https://www.abcxyz.com/) foo
> ```
> 
> Which would result to the following after pasting
> ```
> foo bar
> [bar](https://www.abcxyz.org/) [baz](https://www.abcxyz.com/) bar
> 
> baz baz foo …
```
=> Fix: Pasting of html with similar matches that have links

.eslintrc.json, examples/index.html, package-lock.json, src/index.ts, src/paste-keyboard-shortcut-helper.ts, src/paste-markdown-html.ts, src/paste-markdown-image-link.ts, src/paste-markdown-link.ts, src/paste-markdown-table.ts, src/paste-markdown-text.ts
In https://github.com/github/paste-markdown/pull/97 we upgraded the module output, to output bare esm alongside the bundle. This was broken however, as the file extensions weren't added.
This PR adds those.
=> add missing extensions to modules
